### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by HaraShun**
## Description
How about adding `dependabot` ?

### Reference
[Dependabot で go modules の自動アップデートをする（go mod tidy付き） - Hack Your Design!](https://blog.toshimaru.net/dependabot-gomod/)

[GitHubにDependabotを導入して依存ライブラリを自動アップデートする | DevelopersIO](https://dev.classmethod.jp/articles/github-dependabot-2021/)

[Configuring Dependabot security updates - GitHub Docs](https://docs.github.com/ja/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates)

### CODE REVIEW

**Comment by sheepla** [comment]
Thank you for your pull req. Wow, It seems to be very convenient. I'll try it! 👍

**Comment by HaraShun** [comment]
@sheepla

Thank you for your quick merge !
I hope that this tool will be loved by many people.

**Comment by HaraShun** [comment]
@sheepla 

Plz don't forget to enable these settings ~ ✋

image

image

**Comment by sheepla** [comment]
🙏✨

**Pull request merged**
